spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: click-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  application:
    name: tinyurl
  datasource:
    url: jdbc:mysql://localhost:3306/url_shortener
    username: root
    password: INDIANa@1992
  data:
    redis:
      host: localhost 
      port: 6379

app:
    base-url: http://localhost:8080/